### ISSUE TITLE
about our HM

### ISSUE THREAD

**Issue by jalalalwani** [JawharBairakdar/GitHub-HD#1]
HI Jawhar, you did really a good job , but i have a few remarks about few things:
1 - In Q:02 you supposed not to use  filter inside the function but to pass the argument funtcion through your array and the funtion should filter out what you want to do, this is the callback , in your case you did every this ready and the argument's functions do only the console.log . you are going to check mine Hm so you can understand what i mean 100%.

2- for the bouns part from the HM , it's true you did it in a complicated  way but as you get the target result there in nothing to commit about , welldone.

**Comment by JawharBairakdar** [comment]
Yeah Thanks for your feedback, it's true may next time for the Q.2 :grin:
